### ISSUE TITLE
'as const' in generated code

### ISSUE THREAD

**Issue by unknwngera** [Voldemat/tech-spec#1]
Hi, is it possible to add 'as const' to every autogenerated object in spec (e.g. design system)? It could improve autocomplete and provide more info about each field.

<img width="266" alt="image" src="https://github.com/Voldemat/tech-spec/assets/108179125/79b7544e-a653-4086-ba98-e5af3f28002c">
<img width="314" alt="image" src="https://github.com/Voldemat/tech-spec/assets/108179125/e9a8b250-3a49-4a71-93ff-1c688aca4eef">

**Comment by Voldemat** [comment]
Hi, added "as const" in 1.0.55 version. Feel free to reopen issue if you will encounter some problems with it
